name: Daily TV Program Schedule

on:
  schedule:
    # Запуск в 17:00 UTC+3 (14:00 UTC)
    - cron: '0 14 * * *'
  workflow_dispatch: # Позволяет запускать workflow вручную

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TV program script
        env:
          KINOPOISK_API_KEY: ${{ secrets.KINOPOISK_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node index.js
